const data = {
  products: [
    {
      name: 'Free Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Camisa popular',
    },
    {
      name: 'Fit Shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 870,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Camisa popular',
    },
    {
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Camisa popular',
    },
    {
      name: 'Golf Pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Produto de boa qualidade',
    },
    {
      name: 'fit Pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 70,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Qualidade aceitavel',
    },
    {
      name: 'Classic Pants',
      category: 'Shirts',
      image: '/images/pants3.jpg',
      price: 170,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Popular',
    },
  ],
};

export default data;
